// This file was generated by tfxjs
const tfxjs = require("tfxjs");
const tfx = new tfxjs("../", {
  ibmcloud_api_key: process.env.API_KEY,
  prefix: "at-3-zone",
  region: "us-south",
  zones: 3,
  entitlement: "cloud_pak",
  flavor: "bx2.16x64",
  cluster_type: "iks",
  worker_pool_names: ["test"],
  use_worker_pool_json: true,
});

tfx.plan("tfx Generated Plan", () => {
  tfx.module(
    "Root Module",
    "root_module",
    tfx.resource(
      "Easy Cluster To Kms Cluster To Kms",
      'ibm_iam_authorization_policy.easy_cluster_to_kms["cluster-to-kms"]',
      {
        description:
          "Allow cluster worker pools to be encrypted by Key Management instance.",
        roles: ["Reader", "Authorization Delegator"],
        source_service_name: "containers-kubernetes",
        target_service_name: "kms",
      }
    ),
    tfx.resource("Cluster Key", "ibm_kms_key.cluster_key", {
      endpoint_type: "public",
      force_delete: false,
      key_name: "at-3-zone-cluster-key",
      key_ring_id: "default",
      standard_key: false,
    }),
    tfx.resource(
      "Resource Group Management",
      'ibm_resource_group.resource_group["management"]',
      {
        name: "at-3-zone-management-rg",
      }
    )
  );

  tfx.module(
    "Clusters Workload",
    'module.clusters["workload"]',
    tfx.resource("Cluster", "ibm_container_vpc_cluster.cluster", {
      disable_public_service_endpoint: false,
      entitlement: "cloud_pak",
      flavor: "bx2.16x64",
      force_delete_storage: false,
      image_security_enforcement: false,
      kms_config: [
        {
          private_endpoint: true,
        },
      ],
      kube_version: "1.24.2",
      name: "at-3-zone-roks-cluster",
      
      taints: [],
      timeouts: {
        create: "3h",
        delete: "2h",
        update: "3h",
      },
      update_all_workers: false,
      wait_for_worker_update: true,
      wait_till: "IngressReady",
      worker_count: 2,
      zones: [
        {
          name: "us-south-1",
        },
        {
          name: "us-south-2",
        },
        {
          name: "us-south-3",
        },
      ],
    })
  );

  tfx.module(
    "Detailed Worker Pools Example Pool",
    'module.detailed_worker_pools["example-pool"]',
    tfx.resource("Pool", "ibm_container_vpc_worker_pool.pool", {
      flavor: "bx2.16x64",
      taints: [],
      worker_count: 2,
      worker_pool_name: "at-3-zone-example-pool",
      zones: [
        {
          name: "us-south-1",
        },
        {
          name: "us-south-2",
        },
        {
          name: "us-south-3",
        },
      ],
    })
  );

  tfx.module(
    "Easy Worker Pools Workload Test",
    'module.easy_worker_pools["workload-test"]',
    tfx.resource("Pool", "ibm_container_vpc_worker_pool.pool", {
      flavor: "bx2.16x64",
      taints: [],
      worker_count: 2,
      worker_pool_name: "at-3-zone-workload-test",
      zones: [
        {
          name: "us-south-1",
        },
        {
          name: "us-south-2",
        },
        {
          name: "us-south-3",
        },
      ],
    })
  );

  tfx.module(
    "Icse Vpc Network",
    "module.icse_vpc_network",
    tfx.resource("Format Output", "data.external.format_output", {
      program: ["python3", "vpc_module/scripts/output.py", null],
    })
  );

  tfx.module(
    "Cloud Object Storage",
    "module.icse_vpc_network.module.services.module.cloud_object_storage",
    tfx.resource(
      "Bucket Atracker Bucket",
      'ibm_cos_bucket.bucket["atracker-bucket"]',
      {
        abort_incomplete_multipart_upload_days: [],
        activity_tracking: [],
        archive_rule: [],
        endpoint_type: "public",
        expire_rule: [],
        force_delete: true,
        metrics_monitoring: [],
        noncurrent_version_expiration: [],
        object_versioning: [],
        region_location: "us-south",
        retention_rule: [],
        storage_class: "standard",
      }
    ),
    tfx.resource(
      "Bucket Management Flow Logs Bucket",
      'ibm_cos_bucket.bucket["management-flow-logs-bucket"]',
      {
        abort_incomplete_multipart_upload_days: [],
        activity_tracking: [],
        archive_rule: [],
        endpoint_type: "public",
        expire_rule: [],
        force_delete: true,
        metrics_monitoring: [],
        noncurrent_version_expiration: [],
        object_versioning: [],
        region_location: "us-south",
        retention_rule: [],
        storage_class: "standard",
      }
    ),
    tfx.resource(
      "Bucket Workload Flow Logs Bucket",
      'ibm_cos_bucket.bucket["workload-flow-logs-bucket"]',
      {
        abort_incomplete_multipart_upload_days: [],
        activity_tracking: [],
        archive_rule: [],
        endpoint_type: "public",
        expire_rule: [],
        force_delete: true,
        metrics_monitoring: [],
        noncurrent_version_expiration: [],
        object_versioning: [],
        region_location: "us-south",
        retention_rule: [],
        storage_class: "standard",
      }
    ),
    tfx.resource("Cos Cos", 'ibm_resource_instance.cos["cos"]', {
      location: "global",
      plan: "standard",
      service: "cloud-object-storage",
    }),
    tfx.resource("Random Cos Suffix", "random_string.random_cos_suffix", {
      length: 8,
      lower: true,
      min_lower: 0,
      min_numeric: 0,
      min_special: 0,
      min_upper: 0,
      number: true,
      numeric: true,
      special: false,
      upper: false,
    })
  );

  tfx.module(
    "Key Management Key Management",
    'module.icse_vpc_network.module.services.module.key_management["key_management"]',
    tfx.resource(
      "Block Storage Policy 0",
      "ibm_iam_authorization_policy.block_storage_policy[0]",
      {
        description:
          "Allow block storage volumes to be encrypted by Key Management instance.",
        roles: ["Reader", "Authorization Delegator"],
        source_resource_type: "share",
        source_service_name: "is",
        target_service_name: "kms",
      }
    ),
    tfx.resource(
      "Server Protect Policy 0",
      "ibm_iam_authorization_policy.server_protect_policy[0]",
      {
        description:
          "Allow block storage volumes to be encrypted by Key Management instance.",
        roles: ["Reader"],
        source_service_name: "server-protect",
        target_service_name: "kms",
      }
    ),
    tfx.resource("Key Bucket Key", 'ibm_kms_key.key["bucket-key"]', {
      force_delete: true,
      key_name: "at-3-zone-bucket-key",
      key_ring_id: "default",
      standard_key: false,
    }),
    tfx.resource("Kms 0", "ibm_resource_instance.kms[0]", {
      location: "us-south",
      name: "at-3-zone-kms",
      plan: "tiered-pricing",
      service: "kms",
    })
  );

  tfx.module(
    "Vpc",
    "module.icse_vpc_network.module.vpc",
    tfx.resource("Format Output", "data.external.format_output", {
      program: [
        "python3",
        ".terraform/modules/icse_vpc_network.vpc/scripts/output.py",
        null,
      ],
    }),
    tfx.resource(
      "Connection Management",
      'ibm_tg_connection.connection["management"]',
      {
        name: "at-3-zone-management-hub-connection",
        network_type: "vpc",
        timeouts: {
          create: "30m",
          delete: "30m",
          update: null
        },
      }
    ),
    tfx.resource(
      "Connection Workload",
      'ibm_tg_connection.connection["workload"]',
      {
        name: "at-3-zone-workload-hub-connection",
        network_type: "vpc",
        timeouts: {
          create: "30m",
          delete: "30m",
          update: null        
        },
      }
    ),
    tfx.resource("Transit Gateway 0", "ibm_tg_gateway.transit_gateway[0]", {
      global: false,
      location: "us-south",
      name: "at-3-zone-transit-gateway",
      timeouts: {
        create: "30m",
        delete: "30m",
        update: null
      },
    })
  );

  tfx.module(
    "Vpcs Management",
    'module.icse_vpc_network.module.vpc.module.vpcs["management"]',
    tfx.resource("Vpc", "ibm_is_vpc.vpc", {
      address_prefix_management: "auto",
      classic_access: false,
      name: "at-3-zone-management-vpc",
    })
  );

  tfx.module(
    "Public Gateways",
    'module.icse_vpc_network.module.vpc.module.vpcs["management"].module.public_gateways',
    tfx.resource("Gateway Zone 1", 'ibm_is_public_gateway.gateway["zone-1"]', {
      name: "at-3-zone-management-public-gateway-zone-1",
      zone: "us-south-1",
    })
  );

  tfx.module(
    "Network Acls",
    'module.icse_vpc_network.module.vpc.module.vpcs["management"].module.network_acls',
    tfx.resource("Acl Vpe Acl", 'ibm_is_network_acl.acl["vpe-acl"]', {
      name: "at-3-zone-management-vpe-acl",
      rules: [
        {
          action: "allow",
          destination: "10.0.0.0/8",
          direction: "inbound",
          icmp: [],
          name: "roks-create-worker-nodes-inbound",
          source: "161.26.0.0/16",
          tcp: [],
          udp: [],
        },
        {
          action: "allow",
          destination: "161.26.0.0/16",
          direction: "outbound",
          icmp: [],
          name: "roks-create-worker-nodes-outbound",
          source: "10.0.0.0/8",
          tcp: [],
          udp: [],
        },
        {
          action: "allow",
          destination: "10.0.0.0/8",
          direction: "inbound",
          icmp: [],
          name: "roks-nodes-to-service-inbound",
          source: "166.8.0.0/14",
          tcp: [],
          udp: [],
        },
        {
          action: "allow",
          destination: "166.8.0.0/14",
          direction: "outbound",
          icmp: [],
          name: "roks-nodes-to-service-outbound",
          source: "10.0.0.0/8",
          tcp: [],
          udp: [],
        },
        {
          action: "allow",
          destination: "10.0.0.0/8",
          direction: "inbound",
          icmp: [],
          name: "allow-app-incoming-traffic-requests",
          source: "10.0.0.0/8",
          tcp: [
            {
              port_max: 65535,
              port_min: 1,
              source_port_max: 30000,
              source_port_min: 30000,
            },
          ],
          udp: [],
        },
        {
          action: "allow",
          destination: "10.0.0.0/8",
          direction: "outbound",
          icmp: [],
          name: "allow-app-outgoing-traffic-requests",
          source: "10.0.0.0/8",
          tcp: [
            {
              port_max: 32767,
              port_min: 30000,
              source_port_max: 65535,
              source_port_min: 1,
            },
          ],
          udp: [],
        },
        {
          action: "allow",
          destination: "10.0.0.0/8",
          direction: "inbound",
          icmp: [],
          name: "allow-lb-incoming-traffic-requests",
          source: "10.0.0.0/8",
          tcp: [
            {
              port_max: 443,
              port_min: 443,
              source_port_max: 65535,
              source_port_min: 1,
            },
          ],
          udp: [],
        },
        {
          action: "allow",
          destination: "10.0.0.0/8",
          direction: "outbound",
          icmp: [],
          name: "allow-lb-outgoing-traffic-requests",
          source: "10.0.0.0/8",
          tcp: [
            {
              port_max: 65535,
              port_min: 1,
              source_port_max: 443,
              source_port_min: 443,
            },
          ],
          udp: [],
        },
        {
          action: "allow",
          destination: "10.0.0.0/8",
          direction: "inbound",
          icmp: [],
          name: "vpe-allow-inbound-1",
          source: "10.0.0.0/8",
          tcp: [],
          udp: [],
        },
        {
          action: "allow",
          destination: "10.0.0.0/8",
          direction: "inbound",
          icmp: [],
          name: "vpe-allow-inbound-2",
          source: "161.26.0.0/16",
          tcp: [],
          udp: [],
        },
        {
          action: "allow",
          destination: "0.0.0.0/0",
          direction: "outbound",
          icmp: [],
          name: "vpe-allow-outbound-1",
          source: "10.0.0.0/8",
          tcp: [],
          udp: [],
        },
        {
          action: "deny",
          destination: "10.0.0.0/8",
          direction: "inbound",
          icmp: [],
          name: "vpe-deny-inbound-1",
          source: "0.0.0.0/0",
          tcp: [],
          udp: [],
        },
      ],
    }),
    tfx.resource("Acl Vpn Acl", 'ibm_is_network_acl.acl["vpn-acl"]', {
      name: "at-3-zone-management-vpn-acl",
      rules: [
        {
          action: "allow",
          destination: "10.0.0.0/8",
          direction: "inbound",
          icmp: [],
          name: "roks-create-worker-nodes-inbound",
          source: "161.26.0.0/16",
          tcp: [],
          udp: [],
        },
        {
          action: "allow",
          destination: "161.26.0.0/16",
          direction: "outbound",
          icmp: [],
          name: "roks-create-worker-nodes-outbound",
          source: "10.0.0.0/8",
          tcp: [],
          udp: [],
        },
        {
          action: "allow",
          destination: "10.0.0.0/8",
          direction: "inbound",
          icmp: [],
          name: "roks-nodes-to-service-inbound",
          source: "166.8.0.0/14",
          tcp: [],
          udp: [],
        },
        {
          action: "allow",
          destination: "166.8.0.0/14",
          direction: "outbound",
          icmp: [],
          name: "roks-nodes-to-service-outbound",
          source: "10.0.0.0/8",
          tcp: [],
          udp: [],
        },
        {
          action: "allow",
          destination: "10.0.0.0/8",
          direction: "inbound",
          icmp: [],
          name: "allow-app-incoming-traffic-requests",
          source: "10.0.0.0/8",
          tcp: [
            {
              port_max: 65535,
              port_min: 1,
              source_port_max: 30000,
              source_port_min: 30000,
            },
          ],
          udp: [],
        },
        {
          action: "allow",
          destination: "10.0.0.0/8",
          direction: "outbound",
          icmp: [],
          name: "allow-app-outgoing-traffic-requests",
          source: "10.0.0.0/8",
          tcp: [
            {
              port_max: 32767,
              port_min: 30000,
              source_port_max: 65535,
              source_port_min: 1,
            },
          ],
          udp: [],
        },
        {
          action: "allow",
          destination: "10.0.0.0/8",
          direction: "inbound",
          icmp: [],
          name: "allow-lb-incoming-traffic-requests",
          source: "10.0.0.0/8",
          tcp: [
            {
              port_max: 443,
              port_min: 443,
              source_port_max: 65535,
              source_port_min: 1,
            },
          ],
          udp: [],
        },
        {
          action: "allow",
          destination: "10.0.0.0/8",
          direction: "outbound",
          icmp: [],
          name: "allow-lb-outgoing-traffic-requests",
          source: "10.0.0.0/8",
          tcp: [
            {
              port_max: 65535,
              port_min: 1,
              source_port_max: 443,
              source_port_min: 443,
            },
          ],
          udp: [],
        },
        {
          action: "allow",
          destination: "10.0.0.0/8",
          direction: "inbound",
          icmp: [],
          name: "vpn-allow-inbound-1",
          source: "10.0.0.0/8",
          tcp: [],
          udp: [],
        },
        {
          action: "allow",
          destination: "10.0.0.0/8",
          direction: "inbound",
          icmp: [],
          name: "vpn-allow-inbound-2",
          source: "161.26.0.0/16",
          tcp: [],
          udp: [],
        },
        {
          action: "allow",
          destination: "0.0.0.0/0",
          direction: "outbound",
          icmp: [],
          name: "vpn-allow-outbound-1",
          source: "10.0.0.0/8",
          tcp: [],
          udp: [],
        },
        {
          action: "deny",
          destination: "10.0.0.0/8",
          direction: "inbound",
          icmp: [],
          name: "vpn-deny-inbound-1",
          source: "0.0.0.0/0",
          tcp: [],
          udp: [],
        },
      ],
    }),
    tfx.resource("Acl Vsi Acl", 'ibm_is_network_acl.acl["vsi-acl"]', {
      name: "at-3-zone-management-vsi-acl",
      rules: [
        {
          action: "allow",
          destination: "10.0.0.0/8",
          direction: "inbound",
          icmp: [],
          name: "roks-create-worker-nodes-inbound",
          source: "161.26.0.0/16",
          tcp: [],
          udp: [],
        },
        {
          action: "allow",
          destination: "161.26.0.0/16",
          direction: "outbound",
          icmp: [],
          name: "roks-create-worker-nodes-outbound",
          source: "10.0.0.0/8",
          tcp: [],
          udp: [],
        },
        {
          action: "allow",
          destination: "10.0.0.0/8",
          direction: "inbound",
          icmp: [],
          name: "roks-nodes-to-service-inbound",
          source: "166.8.0.0/14",
          tcp: [],
          udp: [],
        },
        {
          action: "allow",
          destination: "166.8.0.0/14",
          direction: "outbound",
          icmp: [],
          name: "roks-nodes-to-service-outbound",
          source: "10.0.0.0/8",
          tcp: [],
          udp: [],
        },
        {
          action: "allow",
          destination: "10.0.0.0/8",
          direction: "inbound",
          icmp: [],
          name: "allow-app-incoming-traffic-requests",
          source: "10.0.0.0/8",
          tcp: [
            {
              port_max: 65535,
              port_min: 1,
              source_port_max: 30000,
              source_port_min: 30000,
            },
          ],
          udp: [],
        },
        {
          action: "allow",
          destination: "10.0.0.0/8",
          direction: "outbound",
          icmp: [],
          name: "allow-app-outgoing-traffic-requests",
          source: "10.0.0.0/8",
          tcp: [
            {
              port_max: 32767,
              port_min: 30000,
              source_port_max: 65535,
              source_port_min: 1,
            },
          ],
          udp: [],
        },
        {
          action: "allow",
          destination: "10.0.0.0/8",
          direction: "inbound",
          icmp: [],
          name: "allow-lb-incoming-traffic-requests",
          source: "10.0.0.0/8",
          tcp: [
            {
              port_max: 443,
              port_min: 443,
              source_port_max: 65535,
              source_port_min: 1,
            },
          ],
          udp: [],
        },
        {
          action: "allow",
          destination: "10.0.0.0/8",
          direction: "outbound",
          icmp: [],
          name: "allow-lb-outgoing-traffic-requests",
          source: "10.0.0.0/8",
          tcp: [
            {
              port_max: 65535,
              port_min: 1,
              source_port_max: 443,
              source_port_min: 443,
            },
          ],
          udp: [],
        },
        {
          action: "allow",
          destination: "10.0.0.0/8",
          direction: "inbound",
          icmp: [],
          name: "vsi-allow-inbound-1",
          source: "10.0.0.0/8",
          tcp: [],
          udp: [],
        },
        {
          action: "allow",
          destination: "10.0.0.0/8",
          direction: "inbound",
          icmp: [],
          name: "vsi-allow-inbound-2",
          source: "161.26.0.0/16",
          tcp: [],
          udp: [],
        },
        {
          action: "allow",
          destination: "0.0.0.0/0",
          direction: "outbound",
          icmp: [],
          name: "vsi-allow-outbound-1",
          source: "10.0.0.0/8",
          tcp: [],
          udp: [],
        },
        {
          action: "deny",
          destination: "10.0.0.0/8",
          direction: "inbound",
          icmp: [],
          name: "vsi-deny-inbound-1",
          source: "0.0.0.0/0",
          tcp: [],
          udp: [],
        },
      ],
    })
  );

  tfx.module(
    "Subnets",
    'module.icse_vpc_network.module.vpc.module.vpcs["management"].module.subnets',
    tfx.resource(
      "Subnet At 3 Zone Management Vpe 1",
      'ibm_is_subnet.subnet["at-3-zone-management-vpe-1"]',
      {
        ip_version: "ipv4",
        ipv4_cidr_block: "10.10.20.0/24",
        name: "at-3-zone-management-vpe-1",
        zone: "us-south-1",
      }
    ),
    tfx.resource(
      "Subnet At 3 Zone Management Vpe 2",
      'ibm_is_subnet.subnet["at-3-zone-management-vpe-2"]',
      {
        ip_version: "ipv4",
        ipv4_cidr_block: "10.20.20.0/24",
        name: "at-3-zone-management-vpe-2",
        zone: "us-south-2",
      }
    ),
    tfx.resource(
      "Subnet At 3 Zone Management Vpe 3",
      'ibm_is_subnet.subnet["at-3-zone-management-vpe-3"]',
      {
        ip_version: "ipv4",
        ipv4_cidr_block: "10.30.20.0/24",
        name: "at-3-zone-management-vpe-3",
        zone: "us-south-3",
      }
    ),
    tfx.resource(
      "Subnet At 3 Zone Management Vpn 1",
      'ibm_is_subnet.subnet["at-3-zone-management-vpn-1"]',
      {
        ip_version: "ipv4",
        ipv4_cidr_block: "10.0.30.0/24",
        name: "at-3-zone-management-vpn-1",
        zone: "us-south-1",
      }
    ),
    tfx.resource(
      "Subnet At 3 Zone Management Vsi 1",
      'ibm_is_subnet.subnet["at-3-zone-management-vsi-1"]',
      {
        ip_version: "ipv4",
        ipv4_cidr_block: "10.10.10.0/24",
        name: "at-3-zone-management-vsi-1",
        zone: "us-south-1",
      }
    ),
    tfx.resource(
      "Subnet At 3 Zone Management Vsi 2",
      'ibm_is_subnet.subnet["at-3-zone-management-vsi-2"]',
      {
        ip_version: "ipv4",
        ipv4_cidr_block: "10.20.10.0/24",
        name: "at-3-zone-management-vsi-2",
        zone: "us-south-2",
      }
    ),
    tfx.resource(
      "Subnet At 3 Zone Management Vsi 3",
      'ibm_is_subnet.subnet["at-3-zone-management-vsi-3"]',
      {
        ip_version: "ipv4",
        ipv4_cidr_block: "10.30.10.0/24",
        name: "at-3-zone-management-vsi-3",
        zone: "us-south-3",
      }
    ),
    tfx.resource(
      "Subnet Prefix At 3 Zone Management Vpe 1",
      'ibm_is_vpc_address_prefix.subnet_prefix["at-3-zone-management-vpe-1"]',
      {
        cidr: "10.10.20.0/24",
        is_default: false,
        name: "at-3-zone-management-vpe-1",
        zone: "us-south-1",
      }
    ),
    tfx.resource(
      "Subnet Prefix At 3 Zone Management Vpe 2",
      'ibm_is_vpc_address_prefix.subnet_prefix["at-3-zone-management-vpe-2"]',
      {
        cidr: "10.20.20.0/24",
        is_default: false,
        name: "at-3-zone-management-vpe-2",
        zone: "us-south-2",
      }
    ),
    tfx.resource(
      "Subnet Prefix At 3 Zone Management Vpe 3",
      'ibm_is_vpc_address_prefix.subnet_prefix["at-3-zone-management-vpe-3"]',
      {
        cidr: "10.30.20.0/24",
        is_default: false,
        name: "at-3-zone-management-vpe-3",
        zone: "us-south-3",
      }
    ),
    tfx.resource(
      "Subnet Prefix At 3 Zone Management Vpn 1",
      'ibm_is_vpc_address_prefix.subnet_prefix["at-3-zone-management-vpn-1"]',
      {
        cidr: "10.0.30.0/24",
        is_default: false,
        name: "at-3-zone-management-vpn-1",
        zone: "us-south-1",
      }
    ),
    tfx.resource(
      "Subnet Prefix At 3 Zone Management Vsi 1",
      'ibm_is_vpc_address_prefix.subnet_prefix["at-3-zone-management-vsi-1"]',
      {
        cidr: "10.10.10.0/24",
        is_default: false,
        name: "at-3-zone-management-vsi-1",
        zone: "us-south-1",
      }
    ),
    tfx.resource(
      "Subnet Prefix At 3 Zone Management Vsi 2",
      'ibm_is_vpc_address_prefix.subnet_prefix["at-3-zone-management-vsi-2"]',
      {
        cidr: "10.20.10.0/24",
        is_default: false,
        name: "at-3-zone-management-vsi-2",
        zone: "us-south-2",
      }
    ),
    tfx.resource(
      "Subnet Prefix At 3 Zone Management Vsi 3",
      'ibm_is_vpc_address_prefix.subnet_prefix["at-3-zone-management-vsi-3"]',
      {
        cidr: "10.30.10.0/24",
        is_default: false,
        name: "at-3-zone-management-vsi-3",
        zone: "us-south-3",
      }
    )
  );

  tfx.module(
    "Vpn Gateway",
    'module.icse_vpc_network.module.vpc.module.vpcs["management"].module.vpn_gateway',
    tfx.resource("Gateway 0", "ibm_is_vpn_gateway.gateway[0]", {
      mode: "route",
      name: "at-3-zone-management-vpn-gateway",
      timeouts: {
        delete: "1h",
        create: null
      },
    })
  );

  tfx.module(
    "Vpcs Workload",
    'module.icse_vpc_network.module.vpc.module.vpcs["workload"]',
    tfx.resource("Vpc", "ibm_is_vpc.vpc", {
      address_prefix_management: "auto",
      classic_access: false,
      name: "at-3-zone-workload-vpc",
    })
  );

  tfx.module(
    "Network Acls",
    'module.icse_vpc_network.module.vpc.module.vpcs["workload"].module.network_acls',
    tfx.resource("Acl Vpe Acl", 'ibm_is_network_acl.acl["vpe-acl"]', {
      name: "at-3-zone-workload-vpe-acl",
      rules: [
        {
          action: "allow",
          destination: "10.0.0.0/8",
          direction: "inbound",
          icmp: [],
          name: "roks-create-worker-nodes-inbound",
          source: "161.26.0.0/16",
          tcp: [],
          udp: [],
        },
        {
          action: "allow",
          destination: "161.26.0.0/16",
          direction: "outbound",
          icmp: [],
          name: "roks-create-worker-nodes-outbound",
          source: "10.0.0.0/8",
          tcp: [],
          udp: [],
        },
        {
          action: "allow",
          destination: "10.0.0.0/8",
          direction: "inbound",
          icmp: [],
          name: "roks-nodes-to-service-inbound",
          source: "166.8.0.0/14",
          tcp: [],
          udp: [],
        },
        {
          action: "allow",
          destination: "166.8.0.0/14",
          direction: "outbound",
          icmp: [],
          name: "roks-nodes-to-service-outbound",
          source: "10.0.0.0/8",
          tcp: [],
          udp: [],
        },
        {
          action: "allow",
          destination: "10.0.0.0/8",
          direction: "inbound",
          icmp: [],
          name: "allow-app-incoming-traffic-requests",
          source: "10.0.0.0/8",
          tcp: [
            {
              port_max: 65535,
              port_min: 1,
              source_port_max: 30000,
              source_port_min: 30000,
            },
          ],
          udp: [],
        },
        {
          action: "allow",
          destination: "10.0.0.0/8",
          direction: "outbound",
          icmp: [],
          name: "allow-app-outgoing-traffic-requests",
          source: "10.0.0.0/8",
          tcp: [
            {
              port_max: 32767,
              port_min: 30000,
              source_port_max: 65535,
              source_port_min: 1,
            },
          ],
          udp: [],
        },
        {
          action: "allow",
          destination: "10.0.0.0/8",
          direction: "inbound",
          icmp: [],
          name: "allow-lb-incoming-traffic-requests",
          source: "10.0.0.0/8",
          tcp: [
            {
              port_max: 443,
              port_min: 443,
              source_port_max: 65535,
              source_port_min: 1,
            },
          ],
          udp: [],
        },
        {
          action: "allow",
          destination: "10.0.0.0/8",
          direction: "outbound",
          icmp: [],
          name: "allow-lb-outgoing-traffic-requests",
          source: "10.0.0.0/8",
          tcp: [
            {
              port_max: 65535,
              port_min: 1,
              source_port_max: 443,
              source_port_min: 443,
            },
          ],
          udp: [],
        },
        {
          action: "allow",
          destination: "10.0.0.0/8",
          direction: "inbound",
          icmp: [],
          name: "vpe-allow-inbound-1",
          source: "10.0.0.0/8",
          tcp: [],
          udp: [],
        },
        {
          action: "allow",
          destination: "10.0.0.0/8",
          direction: "inbound",
          icmp: [],
          name: "vpe-allow-inbound-2",
          source: "161.26.0.0/16",
          tcp: [],
          udp: [],
        },
        {
          action: "allow",
          destination: "0.0.0.0/0",
          direction: "outbound",
          icmp: [],
          name: "vpe-allow-outbound-1",
          source: "10.0.0.0/8",
          tcp: [],
          udp: [],
        },
        {
          action: "deny",
          destination: "10.0.0.0/8",
          direction: "inbound",
          icmp: [],
          name: "vpe-deny-inbound-1",
          source: "0.0.0.0/0",
          tcp: [],
          udp: [],
        },
      ],
    }),
    tfx.resource("Acl Vsi Acl", 'ibm_is_network_acl.acl["vsi-acl"]', {
      name: "at-3-zone-workload-vsi-acl",
      rules: [
        {
          action: "allow",
          destination: "10.0.0.0/8",
          direction: "inbound",
          icmp: [],
          name: "roks-create-worker-nodes-inbound",
          source: "161.26.0.0/16",
          tcp: [],
          udp: [],
        },
        {
          action: "allow",
          destination: "161.26.0.0/16",
          direction: "outbound",
          icmp: [],
          name: "roks-create-worker-nodes-outbound",
          source: "10.0.0.0/8",
          tcp: [],
          udp: [],
        },
        {
          action: "allow",
          destination: "10.0.0.0/8",
          direction: "inbound",
          icmp: [],
          name: "roks-nodes-to-service-inbound",
          source: "166.8.0.0/14",
          tcp: [],
          udp: [],
        },
        {
          action: "allow",
          destination: "166.8.0.0/14",
          direction: "outbound",
          icmp: [],
          name: "roks-nodes-to-service-outbound",
          source: "10.0.0.0/8",
          tcp: [],
          udp: [],
        },
        {
          action: "allow",
          destination: "10.0.0.0/8",
          direction: "inbound",
          icmp: [],
          name: "allow-app-incoming-traffic-requests",
          source: "10.0.0.0/8",
          tcp: [
            {
              port_max: 65535,
              port_min: 1,
              source_port_max: 30000,
              source_port_min: 30000,
            },
          ],
          udp: [],
        },
        {
          action: "allow",
          destination: "10.0.0.0/8",
          direction: "outbound",
          icmp: [],
          name: "allow-app-outgoing-traffic-requests",
          source: "10.0.0.0/8",
          tcp: [
            {
              port_max: 32767,
              port_min: 30000,
              source_port_max: 65535,
              source_port_min: 1,
            },
          ],
          udp: [],
        },
        {
          action: "allow",
          destination: "10.0.0.0/8",
          direction: "inbound",
          icmp: [],
          name: "allow-lb-incoming-traffic-requests",
          source: "10.0.0.0/8",
          tcp: [
            {
              port_max: 443,
              port_min: 443,
              source_port_max: 65535,
              source_port_min: 1,
            },
          ],
          udp: [],
        },
        {
          action: "allow",
          destination: "10.0.0.0/8",
          direction: "outbound",
          icmp: [],
          name: "allow-lb-outgoing-traffic-requests",
          source: "10.0.0.0/8",
          tcp: [
            {
              port_max: 65535,
              port_min: 1,
              source_port_max: 443,
              source_port_min: 443,
            },
          ],
          udp: [],
        },
        {
          action: "allow",
          destination: "10.0.0.0/8",
          direction: "inbound",
          icmp: [],
          name: "vsi-allow-inbound-1",
          source: "10.0.0.0/8",
          tcp: [],
          udp: [],
        },
        {
          action: "allow",
          destination: "10.0.0.0/8",
          direction: "inbound",
          icmp: [],
          name: "vsi-allow-inbound-2",
          source: "161.26.0.0/16",
          tcp: [],
          udp: [],
        },
        {
          action: "allow",
          destination: "0.0.0.0/0",
          direction: "outbound",
          icmp: [],
          name: "vsi-allow-outbound-1",
          source: "10.0.0.0/8",
          tcp: [],
          udp: [],
        },
        {
          action: "deny",
          destination: "10.0.0.0/8",
          direction: "inbound",
          icmp: [],
          name: "vsi-deny-inbound-1",
          source: "0.0.0.0/0",
          tcp: [],
          udp: [],
        },
      ],
    })
  );

  tfx.module(
    "Subnets",
    'module.icse_vpc_network.module.vpc.module.vpcs["workload"].module.subnets',
    tfx.resource(
      "Subnet At 3 Zone Workload Vpe 1",
      'ibm_is_subnet.subnet["at-3-zone-workload-vpe-1"]',
      {
        ip_version: "ipv4",
        ipv4_cidr_block: "10.40.20.0/24",
        name: "at-3-zone-workload-vpe-1",
        zone: "us-south-1",
      }
    ),
    tfx.resource(
      "Subnet At 3 Zone Workload Vpe 2",
      'ibm_is_subnet.subnet["at-3-zone-workload-vpe-2"]',
      {
        ip_version: "ipv4",
        ipv4_cidr_block: "10.50.20.0/24",
        name: "at-3-zone-workload-vpe-2",
        zone: "us-south-2",
      }
    ),
    tfx.resource(
      "Subnet At 3 Zone Workload Vpe 3",
      'ibm_is_subnet.subnet["at-3-zone-workload-vpe-3"]',
      {
        ip_version: "ipv4",
        ipv4_cidr_block: "10.60.20.0/24",
        name: "at-3-zone-workload-vpe-3",
        zone: "us-south-3",
      }
    ),
    tfx.resource(
      "Subnet At 3 Zone Workload Vsi 1",
      'ibm_is_subnet.subnet["at-3-zone-workload-vsi-1"]',
      {
        ip_version: "ipv4",
        ipv4_cidr_block: "10.40.10.0/24",
        name: "at-3-zone-workload-vsi-1",
        zone: "us-south-1",
      }
    ),
    tfx.resource(
      "Subnet At 3 Zone Workload Vsi 2",
      'ibm_is_subnet.subnet["at-3-zone-workload-vsi-2"]',
      {
        ip_version: "ipv4",
        ipv4_cidr_block: "10.50.10.0/24",
        name: "at-3-zone-workload-vsi-2",
        zone: "us-south-2",
      }
    ),
    tfx.resource(
      "Subnet At 3 Zone Workload Vsi 3",
      'ibm_is_subnet.subnet["at-3-zone-workload-vsi-3"]',
      {
        ip_version: "ipv4",
        ipv4_cidr_block: "10.60.10.0/24",
        name: "at-3-zone-workload-vsi-3",
        zone: "us-south-3",
      }
    ),
    tfx.resource(
      "Subnet Prefix At 3 Zone Workload Vpe 1",
      'ibm_is_vpc_address_prefix.subnet_prefix["at-3-zone-workload-vpe-1"]',
      {
        cidr: "10.40.20.0/24",
        is_default: false,
        name: "at-3-zone-workload-vpe-1",
        zone: "us-south-1",
      }
    ),
    tfx.resource(
      "Subnet Prefix At 3 Zone Workload Vpe 2",
      'ibm_is_vpc_address_prefix.subnet_prefix["at-3-zone-workload-vpe-2"]',
      {
        cidr: "10.50.20.0/24",
        is_default: false,
        name: "at-3-zone-workload-vpe-2",
        zone: "us-south-2",
      }
    ),
    tfx.resource(
      "Subnet Prefix At 3 Zone Workload Vpe 3",
      'ibm_is_vpc_address_prefix.subnet_prefix["at-3-zone-workload-vpe-3"]',
      {
        cidr: "10.60.20.0/24",
        is_default: false,
        name: "at-3-zone-workload-vpe-3",
        zone: "us-south-3",
      }
    ),
    tfx.resource(
      "Subnet Prefix At 3 Zone Workload Vsi 1",
      'ibm_is_vpc_address_prefix.subnet_prefix["at-3-zone-workload-vsi-1"]',
      {
        cidr: "10.40.10.0/24",
        is_default: false,
        name: "at-3-zone-workload-vsi-1",
        zone: "us-south-1",
      }
    ),
    tfx.resource(
      "Subnet Prefix At 3 Zone Workload Vsi 2",
      'ibm_is_vpc_address_prefix.subnet_prefix["at-3-zone-workload-vsi-2"]',
      {
        cidr: "10.50.10.0/24",
        is_default: false,
        name: "at-3-zone-workload-vsi-2",
        zone: "us-south-2",
      }
    ),
    tfx.resource(
      "Subnet Prefix At 3 Zone Workload Vsi 3",
      'ibm_is_vpc_address_prefix.subnet_prefix["at-3-zone-workload-vsi-3"]',
      {
        cidr: "10.60.10.0/24",
        is_default: false,
        name: "at-3-zone-workload-vsi-3",
        zone: "us-south-3",
      }
    )
  );

  tfx.module(
    "Flow Logs",
    "module.icse_vpc_network.module.flow_logs",
    tfx.resource(
      "Flow Logs Policy Cos",
      'ibm_iam_authorization_policy.flow_logs_policy["cos"]',
      {
        description:
          "Allow flow logs write access cloud object storage instance",
        roles: ["Writer"],
        source_resource_type: "flow-log-collector",
        source_service_name: "is",
        target_service_name: "cloud-object-storage",
      }
    ),
    tfx.resource(
      "Flow Logs Management",
      'ibm_is_flow_log.flow_logs["management"]',
      {
        active: true,
        name: "at-3-zone-management-flow-logs",
      }
    ),
    tfx.resource(
      "Flow Logs Workload",
      'ibm_is_flow_log.flow_logs["workload"]',
      {
        active: true,
        name: "at-3-zone-workload-flow-logs",
      }
    )
  );

  tfx.module(
    "Activity Tracker",
    "module.icse_vpc_network.module.activity_tracker",
    tfx.resource(
      "Atracker Target 0",
      "ibm_atracker_target.atracker_target[0]",
      {
        cos_endpoint: [
          {
            endpoint:
              "s3.private.us-south.cloud-object-storage.appdomain.cloud",
            service_to_service_enabled: null,
          },
        ],
        logdna_endpoint: [],
        name: "at-3-zone-atracker",
        target_type: "cloud_object_storage",
      }
    ),
    tfx.resource("Atracker Cos Key 0", "ibm_resource_key.atracker_cos_key[0]", {
      name: "at-3-zone-atracker-cos-bind-key",
      role: "Writer",
    })
  );

  tfx.module(
    "Virtual Private Endpoints Management",
    'module.virtual_private_endpoints["management"]',
    tfx.resource(
      "Ip At 3 Zone Management Vpe 1 Cloud Object Storage Gateway 1 Ip",
      'ibm_is_subnet_reserved_ip.ip["at-3-zone-management-vpe-1-cloud-object-storage-gateway-1-ip"]',
      {}
    ),
    tfx.resource(
      "Ip At 3 Zone Management Vpe 1 Kms Gateway 1 Ip",
      'ibm_is_subnet_reserved_ip.ip["at-3-zone-management-vpe-1-kms-gateway-1-ip"]',
      {}
    ),
    tfx.resource(
      "Ip At 3 Zone Management Vpe 2 Cloud Object Storage Gateway 2 Ip",
      'ibm_is_subnet_reserved_ip.ip["at-3-zone-management-vpe-2-cloud-object-storage-gateway-2-ip"]',
      {}
    ),
    tfx.resource(
      "Ip At 3 Zone Management Vpe 2 Kms Gateway 2 Ip",
      'ibm_is_subnet_reserved_ip.ip["at-3-zone-management-vpe-2-kms-gateway-2-ip"]',
      {}
    ),
    tfx.resource(
      "Ip At 3 Zone Management Vpe 3 Cloud Object Storage Gateway 3 Ip",
      'ibm_is_subnet_reserved_ip.ip["at-3-zone-management-vpe-3-cloud-object-storage-gateway-3-ip"]',
      {}
    ),
    tfx.resource(
      "Ip At 3 Zone Management Vpe 3 Kms Gateway 3 Ip",
      'ibm_is_subnet_reserved_ip.ip["at-3-zone-management-vpe-3-kms-gateway-3-ip"]',
      {}
    ),
    tfx.resource(
      "Vpe Management Cloud Object Storage",
      'ibm_is_virtual_endpoint_gateway.vpe["management-cloud-object-storage"]',
      {
        name: "at-3-zone-management-cloud-object-storage-endpoint-gateway",
        target: [
          {
            crn: "crn:v1:bluemix:public:cloud-object-storage:global:::endpoint:s3.direct.us-south.cloud-object-storage.appdomain.cloud",
            name: null,
            resource_type: "provider_cloud_service",
          },
        ],
      }
    ),
    tfx.resource(
      "Vpe Management Kms",
      'ibm_is_virtual_endpoint_gateway.vpe["management-kms"]',
      {
        name: "at-3-zone-management-kms-endpoint-gateway",
        target: [
          {
            crn: "crn:v1:bluemix:public:kms:us-south:::endpoint:private.us-south.kms.cloud.ibm.com",
            name: null,
            resource_type: "provider_cloud_service",
          },
        ],
      }
    ),
    tfx.resource(
      "Endpoint Gateway Ip At 3 Zone Management Vpe 1 Cloud Object Storage Gateway 1 Ip",
      'ibm_is_virtual_endpoint_gateway_ip.endpoint_gateway_ip["at-3-zone-management-vpe-1-cloud-object-storage-gateway-1-ip"]',
      {}
    ),
    tfx.resource(
      "Endpoint Gateway Ip At 3 Zone Management Vpe 1 Kms Gateway 1 Ip",
      'ibm_is_virtual_endpoint_gateway_ip.endpoint_gateway_ip["at-3-zone-management-vpe-1-kms-gateway-1-ip"]',
      {}
    ),
    tfx.resource(
      "Endpoint Gateway Ip At 3 Zone Management Vpe 2 Cloud Object Storage Gateway 2 Ip",
      'ibm_is_virtual_endpoint_gateway_ip.endpoint_gateway_ip["at-3-zone-management-vpe-2-cloud-object-storage-gateway-2-ip"]',
      {}
    ),
    tfx.resource(
      "Endpoint Gateway Ip At 3 Zone Management Vpe 2 Kms Gateway 2 Ip",
      'ibm_is_virtual_endpoint_gateway_ip.endpoint_gateway_ip["at-3-zone-management-vpe-2-kms-gateway-2-ip"]',
      {}
    ),
    tfx.resource(
      "Endpoint Gateway Ip At 3 Zone Management Vpe 3 Cloud Object Storage Gateway 3 Ip",
      'ibm_is_virtual_endpoint_gateway_ip.endpoint_gateway_ip["at-3-zone-management-vpe-3-cloud-object-storage-gateway-3-ip"]',
      {}
    ),
    tfx.resource(
      "Endpoint Gateway Ip At 3 Zone Management Vpe 3 Kms Gateway 3 Ip",
      'ibm_is_virtual_endpoint_gateway_ip.endpoint_gateway_ip["at-3-zone-management-vpe-3-kms-gateway-3-ip"]',
      {}
    )
  );

  tfx.module(
    "Virtual Private Endpoints Workload",
    'module.virtual_private_endpoints["workload"]',
    tfx.resource(
      "Ip At 3 Zone Workload Vpe 1 Cloud Object Storage Gateway 1 Ip",
      'ibm_is_subnet_reserved_ip.ip["at-3-zone-workload-vpe-1-cloud-object-storage-gateway-1-ip"]',
      {}
    ),
    tfx.resource(
      "Ip At 3 Zone Workload Vpe 1 Kms Gateway 1 Ip",
      'ibm_is_subnet_reserved_ip.ip["at-3-zone-workload-vpe-1-kms-gateway-1-ip"]',
      {}
    ),
    tfx.resource(
      "Ip At 3 Zone Workload Vpe 2 Cloud Object Storage Gateway 2 Ip",
      'ibm_is_subnet_reserved_ip.ip["at-3-zone-workload-vpe-2-cloud-object-storage-gateway-2-ip"]',
      {}
    ),
    tfx.resource(
      "Ip At 3 Zone Workload Vpe 2 Kms Gateway 2 Ip",
      'ibm_is_subnet_reserved_ip.ip["at-3-zone-workload-vpe-2-kms-gateway-2-ip"]',
      {}
    ),
    tfx.resource(
      "Ip At 3 Zone Workload Vpe 3 Cloud Object Storage Gateway 3 Ip",
      'ibm_is_subnet_reserved_ip.ip["at-3-zone-workload-vpe-3-cloud-object-storage-gateway-3-ip"]',
      {}
    ),
    tfx.resource(
      "Ip At 3 Zone Workload Vpe 3 Kms Gateway 3 Ip",
      'ibm_is_subnet_reserved_ip.ip["at-3-zone-workload-vpe-3-kms-gateway-3-ip"]',
      {}
    ),
    tfx.resource(
      "Vpe Workload Cloud Object Storage",
      'ibm_is_virtual_endpoint_gateway.vpe["workload-cloud-object-storage"]',
      {
        name: "at-3-zone-workload-cloud-object-storage-endpoint-gateway",
        target: [
          {
            crn: "crn:v1:bluemix:public:cloud-object-storage:global:::endpoint:s3.direct.us-south.cloud-object-storage.appdomain.cloud",
            name: null,
            resource_type: "provider_cloud_service",
          },
        ],
      }
    ),
    tfx.resource(
      "Vpe Workload Kms",
      'ibm_is_virtual_endpoint_gateway.vpe["workload-kms"]',
      {
        name: "at-3-zone-workload-kms-endpoint-gateway",
        target: [
          {
            crn: "crn:v1:bluemix:public:kms:us-south:::endpoint:private.us-south.kms.cloud.ibm.com",
            name: null,
            resource_type: "provider_cloud_service",
          },
        ],
      }
    ),
    tfx.resource(
      "Endpoint Gateway Ip At 3 Zone Workload Vpe 1 Cloud Object Storage Gateway 1 Ip",
      'ibm_is_virtual_endpoint_gateway_ip.endpoint_gateway_ip["at-3-zone-workload-vpe-1-cloud-object-storage-gateway-1-ip"]',
      {}
    ),
    tfx.resource(
      "Endpoint Gateway Ip At 3 Zone Workload Vpe 1 Kms Gateway 1 Ip",
      'ibm_is_virtual_endpoint_gateway_ip.endpoint_gateway_ip["at-3-zone-workload-vpe-1-kms-gateway-1-ip"]',
      {}
    ),
    tfx.resource(
      "Endpoint Gateway Ip At 3 Zone Workload Vpe 2 Cloud Object Storage Gateway 2 Ip",
      'ibm_is_virtual_endpoint_gateway_ip.endpoint_gateway_ip["at-3-zone-workload-vpe-2-cloud-object-storage-gateway-2-ip"]',
      {}
    ),
    tfx.resource(
      "Endpoint Gateway Ip At 3 Zone Workload Vpe 2 Kms Gateway 2 Ip",
      'ibm_is_virtual_endpoint_gateway_ip.endpoint_gateway_ip["at-3-zone-workload-vpe-2-kms-gateway-2-ip"]',
      {}
    ),
    tfx.resource(
      "Endpoint Gateway Ip At 3 Zone Workload Vpe 3 Cloud Object Storage Gateway 3 Ip",
      'ibm_is_virtual_endpoint_gateway_ip.endpoint_gateway_ip["at-3-zone-workload-vpe-3-cloud-object-storage-gateway-3-ip"]',
      {}
    ),
    tfx.resource(
      "Endpoint Gateway Ip At 3 Zone Workload Vpe 3 Kms Gateway 3 Ip",
      'ibm_is_virtual_endpoint_gateway_ip.endpoint_gateway_ip["at-3-zone-workload-vpe-3-kms-gateway-3-ip"]',
      {}
    )
  );
});
